security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: '$2a$12$BeAFg3/C0WZucDQ6B3ExGuGC/DBjiKFqAFFaZGcxcHYBIbI5GJAmy', roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: in_memory
            form_login:
                login_path: /login
                check_path: /login_check
                enable_csrf: true
            logout:
                path: logout

            # configure the maximum login attempts
            login_throttling:
                max_attempts: 3          # per minute ...
                # interval: '15 minutes' # ... or in a custom period

    access_control:
      - { path: '/secured', roles: ROLE_ADMIN }