
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: en

framework:
  #esi:             ~
  #translator:      { fallbacks: ["%locale%"] }
#  secret: "%secret%"
  router:
#    resource: "%kernel.root_dir%/../config/routes.yaml"
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  #serializer:      { enable_annotations: true }
#  templating:
#    engines: [ 'twig' ]
    #assets_version: SomeVersionScheme
  default_locale: "%locale%"
  trusted_hosts: ~
  session:
    # handler_id set to null will use default session handler from php.ini
    handler_id: ~
    save_path: "%kernel.project_dir%/../var/sessions/%kernel.environment%"
  fragments: ~
  http_method_override: true
  assets: ~

# Twig Configuration
twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  globals:
    separate_days: "%nailit_gallery_separate_days%"
    day_description: "%nailit_gallery_day_from_description%"
    main_path: "%nailit_main_path%"
    page_title: "%nailit_page_title%"
    main_slogan: "%nailit_main_slogan%"
    sort_days: "%nailit_sort_days%"

