security:
    encoders:
        Symfony\Component\Security\Core\User\User: 'bcrypt'
        App\Security\User:
            algorithm: bcrypt

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: '$2a$12$BeAFg3/C0WZucDQ6B3ExGuGC/DBjiKFqAFFaZGcxcHYBIbI5GJAmy', roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: in_memory
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_token_generator: security.csrf.token_manager
            anonymous: ~
            logout:
                path: app_logout

    access_control:
      - { path: '/secured', roles: ROLE_ADMIN }