NailitGalleryBundle_homepage:
    path:  /hello/{name}
    defaults: { _controller: NailitGalleryBundle:Default:index }

gallery:
    path:  /gallery/{year}/{month}/{day}/{file}
    defaults: { _controller: KrzysPageBundle:Default:gallery }