#index:
#    path: /
#    controller: App\Controller\DefaultController::index

NailitGalleryBundle:
  resource: "@NailitGalleryBundle/Resources/config/routing.yml"
  prefix:   /

KrzysPageBundle:
  resource: "@KrzysPageBundle/Resources/config/routing.yml"
  prefix:   /
