gallery:
  path:  /gallery/{year}/{month}/{day}/{file}
  defaults: { _controller: App\Controller\DefaultController::galleryAction }

pageAdminMonth:
  path:  /secured/{year}/{month}
  defaults: { _controller: App\Controller\DefaultController::adminAction }

page_admin:
  path:  /secured
  defaults: { _controller: App\Controller\DefaultController::adminAction }

page_log:
  path:  /log/secured
  defaults: { _controller: App\Controller\DefaultController::logAction }

pageDay:
  path:  /{year}/{month}/{day}
  defaults: { _controller: App\Controller\DefaultController::indexOneDayAction }

evolution:
  path:  /evolution
  defaults: { _controller: App\Controller\DefaultController::evolutionAction }

pageOneDay:
  path:  /oneday/{parameter}
  defaults: { _controller: App\Controller\DefaultController::oneDayAction }

session:
  path:  /session
  defaults: { _controller: App\Controller\DefaultController::sessionAction }

evolutionNoLinks:
  path:  /drw
  defaults: { _controller: App\Controller\DefaultController::evolutionNoLinksAction}

evolutionAdd:
  path:  /evolutionAdd/{year}/{month}/{day}/{file}/{tag}/{week}
  defaults: { _controller: App\Controller\DefaultController::evolutionAddAction }

best:
  path:  /best
  defaults: { _controller: App\Controller\DefaultController::bestAction }

bestNoLinks:
  path:  /spr
  defaults: { _controller: App\Controller\DefaultController::bestNoLinksAction }

bestAdd:
  path:  /bestAdd/{year}/{month}/{day}/{file}
  defaults: { _controller: App\Controller\DefaultController::bestAddAction }

video:
  path:  /video
  defaults: { _controller: App\Controller\DefaultController::videoAction }

hide:
  path:  /hide/{year}/{month}/{day}/{file}
  defaults: { _controller: App\Controller\DefaultController::hideAction }

incoming:
  path:  /incoming
  defaults: { _controller: App\Controller\DefaultController::incomingAction }

incomingAmount:
  path:  /incomingAmount
  defaults: { _controller: App\Controller\DefaultController::incomingAmountAction }


rotate:
  path:  /rotate/{year}/{month}/{day}/{file}/{degrees}
  defaults: { _controller: App\Controller\DefaultController::rotateAction }

tag:
  path:  /tag/{year}/{month}/{day}/{file}
  defaults: { _controller: App\Controller\DefaultController::tagAction }

tagAll:
  path:  /tagAll
  defaults: { _controller: App\Controller\DefaultController::tagAllAction }


description:
  path:  /description/{year}/{month}/{day}/{file}
  defaults: { _controller: App\Controller\DefaultController::descriptionAction }

logout:
  path: /logout
  defaults: { _controller: App\Controller\SecurityController::logout }


login:
  path: /login
  defaults: { _controller: App\Controller\SecurityController::login }

login_check:
  path: /login_check
  defaults: { _controller: App\Controller\SecurityController::loginCheckAction }

pageToo:
  path:  2
  defaults: { _controller: App\Controller\DefaultController::indexAction }

pageMonth:
  path:  /{year}/{month}
  defaults: { _controller: App\Controller\DefaultController::indexAction }

page:
  path: /
  defaults: { _controller: App\Controller\DefaultController::indexAction }

