# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  nailit_filesystem.class: Nailit\GalleryBundle\Entity\Filesystem
  nailit_code.class: Nailit\GalleryBundle\Entity\Code

  nailit_gallery_day_from_description: true #false
  nailit_gallery_separate_days: false #true
  nailit_main_path: krzys #gallery
  nailit_page_title: Krzyś i Zosia #GGG - Grzegorz Gwóźdź Gallery
  nailit_page_subtitle: ...& Zosia ;D #Grzegorz Gwóźdź
  nailit_main_slogan: Oto jesteśmy! #Podróże, małe i duże
  nailit_sort_days: desc #asc

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

        bind:
          $galleryDayFromDescription: '%nailit_gallery_day_from_description%'
          $gallerySeparateDays: '%nailit_gallery_separate_days%'
          $mainPath: '%nailit_main_path%'
          $pageTitle: '%nailit_page_title%'
          $pageSubTitle: '%nailit_page_subtitle%'
          $mainSlogan: '%nailit_main_slogan%'
          $sortDays: '%nailit_sort_days%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
